language: node_js
node_js:
  - "6"
before_install:
- npm i -g npm@5.6.0
script:
  - bash travis-verify-build.sh
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
  - npm run coverage-coveralls

